FROM hub.linux100.cc/library/oracle-java:8-alpine

MAINTAINER triumph2008 <triumph2008@gmail.com>


COPY apache-tomcat-8.0.45.tar.gz /tmp/apache-tomcat-8.0.45.tar.gz

RUN mkdir -p /services/module && \
    tar zxf /tmp/apache-tomcat-8.0.45.tar.gz -C /services/module && \
    ln -s /services/module/apache-tomcat-8.0.45 /services/module/tomcat && \
    rm -rf  /tmp/apache-tomcat-8.0.45.tar.gz 


EXPOSE 8080

ENTRYPOINT ["/services/module/tomcat/bin/catalina.sh","run"]
